### ISSUE TITLE
ADD-events message

### ISSUE THREAD

**Issue by kjaymiller** [OperationCode/operationcode_bot#2]
As a slack member.  When I type `@OC events` It should list some of the upcoming events. This can pull from our airtable calendar.

**Comment by kjaymiller** [comment]
This would be a slash command and webhook

**Comment by rickr** [comment]
I think the slash command works well so users can't spam channels with the response. 

We could also add it as a keyword so users could DM the bot to see upcoming events but that seems like it might be a duplication of efforts.

**Comment by rickr** [comment]
Tracked in https://github.com/OperationCode/operationcode_slash_commands/issues/1.
