### ISSUE TITLE
As a staff member, when a new member joins, we should ask how they were referred to OC for recruitment metrics.

### ISSUE THREAD

**Issue by jdspringr07** [OperationCode/operationcode_bot#20]
We've had explosive growth and haven't really tracked where people are coming from. Not sure if we can handle this via registration or through slackbot.

**Comment by hollomancer** [comment]
Once our user list is in Airtable, we can add a column for this. I'd prefer that we have multiple choices, instead of a text field, since that'll make it easier for us to narrow things down.

**Comment by rickr** [comment]
I think this should be done at sign up time as an optional field. Any disagreements?

**Comment by hollomancer** [comment]
That's cool. What choices should we have?

- Transition Assistance Program
- Code School
- Adwords
- Word of Mouth

**Comment by rickr** [comment]
Maybe an 'Other' as well?

Regardless @jdspringr07 - can you please open a new ticket on the [operationcode](https://github.com/OperationCode/operationcode/issues) repo? 

Closing this issue since we'll be implementing there.
