### ISSUE TITLE
Add link to code of conduct to team join message

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_bot#24]
As a new user, When I am greeted by the bot, It should show a link to the code of conduct
https://github.com/OperationCode/mentorship/blob/master/CODE-OF-CONDUCT.md

**Comment by hollomancer** [comment]
This is an edit to https://github.com/OperationCode/operationcode_bot/blob/master/views/event/team_join/welcome_message.txt.erb - adding a bit to the text there.

**Comment by hollomancer** [comment]
Intent here is to ensure all of our members know the standard mode of behavior expected from them on Slack.

**Comment by rickr** [comment]
Fixed in #62
