### ISSUE TITLE
Export Slack emails to Mailchimp weekly

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_bot#37]
@rickr, not sure where this belongs. We should add a task to the infrastructure, to automatically export our Slack emails to Mailchimp, probably on a weekly basis.

**Comment by rickr** [comment]
This should be happening on sign up: https://github.com/OperationCode/operationcode/blob/master/app/controllers/veterans/registrations_controller.rb#L31 Is that not the case?

**Comment by hollomancer** [comment]
Paging @davidmolina who has been doing this manually

**Comment by davidmolina** [comment]
Nope, it's not. I manually enter them.

**Comment by rickr** [comment]
This is now being handled by the backend.
