### ISSUE TITLE
Add emoji to Reddit integration

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_bot#44]
Tagging a thread with the Reddit emoji cross-posts it to Reddit? Need to understand this better

**Comment by rickr** [comment]
I don't think tagging a whole thread is particularly useful. A good first pass will be the ability to do this to a single message.

For this ticket:

- [ ] Identify an emoji to use (reddit logo?)
- [ ] Subscribe to the reaction_added event:
https://api.slack.com/events/reaction_added
- [ ] On receipt of that event check if our special emoji has been received
- [ ] If yes make an API call to reddit's submit endpoint:
https://www.reddit.com/dev/api/#POST_api_submit

The link posted should be of type text and contain: 
- [ ] The user who made the comment
- [ ] The user who submitted to reddit
- [ ] The contents of the message
- [ ] If possible a link to the message (accessible via slacks archive)

**Comment by rickr** [comment]
Reddit participation seems pretty quiet. @hollomancer do we still want this feature?

**Comment by rickr** [comment]
We'll get something similar once we integrate destalinator so I'm closing this out.
