### ISSUE TITLE
Make team join message clickable

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode_bot#58]
When a new member joins Operation Code a message is sent to the `community` channel.

This message can be seen [here](
https://github.com/OperationCode/operationcode_bot/blob/3f6b8542df3b999fa83c3c0cd44607416f1de49a/lib/event/team_join.rb#L38)

By using slacks message formatting we should be able to make this username clickable.
Documentation can be found [here](https://api.slack.com/docs/message-formatting#linking_to_channels_and_users)

**Comment by Cooperbuilt** [comment]
I think all we need to do is change the team_join.rb file to the following 
<pre>def notify_community!
      im = Operationcode::Slack::Im.new(
        channel: Event::COMMUNITY_CHANNEL,
        text: ":tada: <@#{@user['id']}> has joined the Slack team :tada:"
        )
      im.make_interactive_with!(
        Operationcode::Slack::Im::Interactive.new(
          text: 'Have they been greeted via direct message?',
          id: 'greeted',
          actions: [
            {name: 'yes', text: 'Yes', value: 'yes'}
          ]
        )
      )
      im.deliver
    </pre>
I can't make pull requests on this repo so I will comment it. CAVEAT - not sure if this works

**Comment by rickr** [comment]
Fixed in #60
