### ISSUE TITLE
Adding a mentee logs the date they joined in Airtable

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_bot#7]
As a mentor, I want to see when a mentee joined Operation Code in Airtable, so I know how long they've been a part of the community.

This allows me to get a better sense of which mentees have been waiting the longest for a mentor.

Functional requirements;
- Completion of mentee application populates a column in Airtable with the date submitted.

**Comment by rickr** [comment]
Adding a mentee where? And where is the date logged?

**Comment by rickr** [comment]
This is being done in the operationcode_backend repo.
