### ISSUE TITLE
Change tests to be less reliant on copy

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode_bot#84]
# Feature
## Why is this feature being added?
Any copy changes completely break the tests on operationcode_bot. It should check to see that messages are sent, not that the specific wording is exactly the same.
## What should your feature do?
* `test_it_sends_a_message_to_the_user_if_an_env_var_is_set` just checks to see if a message is sent to the user.
* `test_it_welcomes_the_user_on_new_user_join` just checks to see if a message is sent to the user.

**Comment by hpjaj** [comment]
@hollomancer - I can take this one
